version: '2'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      #- MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS
    volumes:
      - 'mssql_data:/var/opt/mssql'

  keycloak:
    image: docker.ngaviation.eu/ngaviation/keycloak:latest
    depends_on:
      - mssql
    ports:
      - "80:8080"

volumes:
  mssql_data:
    driver: local
